console.log("Family by Carolzita!");
console.log("1°-Mãe:");
console.log("Lucelena Dantas Lino");
console.log("2°-Pai:");
console.log("Donizete Cândido teixeira");
console.log("3°-Irmão:");
console.log("Marcello da GB");
console.log("4°-Avó:");
console.log("Maria Diva Dantas Lino");
console.log("5°-Tio:");
console.log("Lorival Dantas Lino");